name    'bobtfish/postgrey'
version '0.0.1'
author 'bobtfish'
license 'Apache License, Version 2.0'
summary 'A simple module for managing postgrey'
description 'Postgrey is a postfix grey listing system'
project_page 'https://github.com/bobtfish/puppet-postgrey'
source 'git://github.com/bobtfish/puppet-postgrey.git'
dependency 'ripienaar/concat', '>= 0.2.0'

